server:
    port: 80
logging:
    level:
        root: WARN
    file:
        name: /tmp/archivo.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB
    console:
        enabled: false